[package]
name = "two_kings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
eframe = "0.29.1"
egui = "0.29.1"
egui_extras = { version = "0.29.1", features = ["image"] }
env_logger = "0.11.5"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
